name: seafile_server
services:
  db_seafile:
    container_name: seafile-mysql
    environment:
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_PASSWORD=db_dev
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/seafile-mysql/db
        target: /var/lib/mysql
    networks:
      - seafile-net
    privileged: false
  memcached:
    container_name: seafile-memcached
    entrypoint:
      - memcached
      - -m
      - "256"
    image: memcached:1.6.18
    restart: unless-stopped
    networks:
      - seafile-net
    privileged: false
  seafile:
    container_name: seafile
    depends_on:
      db_seafile:
        condition: service_started
        required: true
      memcached:
        condition: service_started
        required: true
    environment:
      - DB_HOST=db_seafile
      - DB_ROOT_PASSWD=db_dev
      - SEAFILE_ADMIN_EMAIL=moran.storm.5050@gmail.com
      - SEAFILE_ADMIN_PASSWORD=sS1123581321$$
      - SEAFILE_SERVER_HOSTNAME=184.107.108.153:8022
      - SEAFILE_SERVER_LETSENCRYPT=false
      - TIME_ZONE=Etc/UTC
    image: seafileltd/seafile-mc:latest
    ports:
      - target: 80
        published: "8022"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Seafile/opt/seafile-data
        target: /shared
    networks:
      - seafile-net
    privileged: false
networks:
  seafile-net:
    name: seafile_server_seafile-net
x-casaos:
  author: Cloudrack.ca
  category: Cloudrack.ca
  icon: https://cdn.imgbin.com/17/6/6/imgbin-seafile-file-hosting-service-cloud-storage-computer-software-installation-raspberries-kKrnZZMLsHAFpQGRC0DLgXXdU.jpg
  index: /
  port_map: "8022"
  scheme: https
  store_app_id: seafile_server
  title:
    custom: Seafile
  description:
    en_us: Seafile is an open-source file sync and share solution designed for high reliability, performance, and productivity. It allows users to sync, share, and collaborate across devices and teams. Seafile provides features similar to Dropbox, Google Drive, and Office 365, while allowing users to host the server on their own hardware. 
  architectures:
    - amd64
    - arm64
    - ppc64le
    - s390x
    - "386"
    - arm
