name: plesk
version: '3'

services:
  plesk:
    container_name: plesk
    image: plesk/plesk
    privileged: true
    ports:
      - "8880:8880/tcp"
      - "80:80/tcp"
      - "8443:8443/tcp"
      - "21:21/tcp"
      - "443:443/tcp"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/sys/fs/cgroup
        target: /sys/fs/cgroup
    network_mode: bridge
x-casaos:
  author: plesk
  category: Developer
  store_app_id: powerful-plesk
  main: plesk
  description:
    en_us: Crafty is an open source Minecraft control panel built using Tornado and AdminLTE, featuring server scheduling, a interactive console and the ability to run almost any type of Minecraft server 
  developer: Cloudrack Team
  icon: https://icon.casaos.io/main/all/plesk.png
  tagline:
    en_us: Take control of your Minecraft servers.
    es_es: Toma el control de tus servidores de Minecraft.
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        |----------|----------|
        | `admin`    | `crafty` |
  title:
    en_us: Plesk
  index: /
  scheme: http
  port_map: "8880"
