name: plesk
version: '3'

services:
  plesk:
    container_name: plesk
    image: plesk/plesk
    privileged: true
    ports:
      - "8880:8880/tcp"
      - "80:80/tcp"
      - "8443:8443/tcp"
      - "21:21/tcp"
      - "443:443/tcp"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/sys/fs/cgroup
        target: /sys/fs/cgroup
    network_mode: bridge
x-casaos:
  author: plesk
  category: Developer
  store_app_id: powerful-plesk
  main: plesk
  description:
    en_us: Plesk is the leading WebOps hosting platform to run, automate and grow applications, websites and hosting businesses. Being the only OS agnostic platform, Plesk is running on more than 384,000 servers, automating 11M+ websites and 15M+ mail boxes. Available in more than 32 languages across 140 countries, 50% of the top 100 service providers worldwide are partnering with Plesk today. 
  developer: Cloudrack Team
  icon: https://icon.casaos.io/main/all/plesk.png
  tagline:
    en_us: Plesk is a leading WebOps hosting platform that offers more than just a control panel. It is designed to help you run, automate, and grow applications, websites, and hosting businesses.
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        |----------|----------|
        | `admin`    | `changeme1Q**` |
  title:
    en_us: Plesk
  index: /
  scheme: http
  port_map: "8880"
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
