name: cloudrack-flarum
services:
  flarum:
    container_name: flarum
    environment:
      - DB_HOST=mariadb
      - DB_NAME=flarum
      - DB_PASS=db-password
      - DB_PORT=3306
      - DB_PREF=flarum_
      - DB_USER=flarum
      - FLARUM_ADMIN_MAIL=admin@example.com
      - FLARUM_ADMIN_PASS=12345678
      - FLARUM_ADMIN_USER=admin
      - FLARUM_TITLE=Flarum Dockerized
      - FORUM_URL=http://10.0.0.202
    image: mondedie/flarum:stable
    ports:
      - target: 8888
        published: "80"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/assets
        target: /flarum/app/public/assets
      - type: bind
        source: /DATA/AppData/$AppID/extensions
        target: /flarum/app/extensions
      - type: bind
        source: /DATA/AppData/$AppID/storage/logs
        target: /flarum/app/storage/logs
      - type: bind
        source: /DATA/AppData/$AppID/nginx
        target: /etc/nginx/flarum
    network_mode: bridge
    privileged: false
  mariadb:
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=flarum
      - MYSQL_PASSWORD=db-password
      - MYSQL_ROOT_PASSWORD=db-root-password
      - MYSQL_USER=flarum
    image: mariadb:10.5
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/mysql/db
        target: /var/lib/mysql
    network_mode: bridge
    privileged: false
x-casaos:
  author: Cloudrack
  category: cms
  hostname: 10.0.0.202
  icon: https://th.bing.com/th/id/R.af1aea0a6379ac4c47a79dd54981c7a2?rik=quv0Sb69jVtqpA&riu=http%3a%2f%2fassets.stickpng.com%2fthumbs%2f62a37be36209494ec2b17080.png&ehk=Hz4bV9CCt6%2fBVyRoMUkFUEsHnbzqZ4PUaoCCrCNxrpE%3d&risl=&pid=ImgRaw&r=0
  index: /
  port_map: "80"
  scheme: http
  store_app_id: cloudrack-flarum
  title:
    custom: flarum
  architectures:
    - amd64
    - arm64
    - arm
