name: wordpress
services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=username
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/db/data
        target: /var/lib/mysql
    networks:
      - db
  wordpress:
    container_name: wordpress
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=database
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=username
    image: wordpress:latest
    labels:
      icon: https://wordpress.org/wp-content/themes/pub/wporg/images/wp-logo-blue.png
    ports:
      - target: 80
        published: "8880"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/wp-content
        target: /var/www/html/wp-content
    networks:
      - db
networks:
  db:
    name: db
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: wordpress # Main service of the application
  description:
    en_us: WordPress (also known as WP or WordPress.org) is a web content management system. It was originally created as a tool to publish blogs but has evolved to support publishing other web content, including more traditional websites, mailing lists and Internet forum, media galleries, membership sites, learning management systems and online stores. Available as free and open-source software, WordPress is among the most popular content management systems – it was used by 42.8% of the top 10 million websites as of October 2021. # Description in English
  tagline:
    en_us: WordPress The Most Powerful CMS You Will Ever Need. # Short description or tagline in English
  developer: Automattic # Developer's name or identifier
  author: Cloudrack # Author of this configuration
  icon: https://wordpress.org/wp-content/themes/pub/wporg/images/wp-logo-blue.png # Icon for the application
  thumbnail: "https://wordpress.org/wp-content/themes/pub/wporg/images/wp-logo-blue.png" # Thumbnail image (currently empty)
  title:
    en_us: Wordpress # Title in English
  category: Cloudrack.ca # Application category
  port_map: "8880" # Port mapping information
  screenshot_link:
    - https://i.ibb.co/fSMFLWD/Word-Press-Post-960x600-896x560.png
  index: /
  scheme: http
  store_app_id: cloudrack-wordpress
